first_flask_project/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort,
                   Blueprint)
from flask_login import current_user, login_required
from first_flask_project import db
from first_flask_project.models import Post, Comment
from first_flask_project.posts.forms import PostForm, CommentForm
from first_flask_project.posts.utils import save_picture

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    """
    Все статьи
    :return:
    """
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.created.desc()).paginate(
        page=page, per_page=5)
    return render_template('allpost.html', posts=posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    """
    Создание новой статьи
    :return:
    """
    form = PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_name = save_picture(form.picture.data)
            image_file = picture_name
        post = Post(title=form.title.data, description=form.description.data,
                    content=form.content.data, author=current_user,
                    image_file=image_file)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html',
                           title='Новый пост', image_file=form.picture.data,
                           form=form, legend='Новый пост')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    """
    Статья
    :param post_id:
    :return:
    """
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.comment.data, post_id=post_id,
                          username=current_user.username)
        db.session.add(comment)
        db.session.commit()
        flash('Ваш комментарий был создан.', 'success')
        return redirect(request.url)

    return render_template('post.html', title=post.title, post=post, form=form)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """
    Редактирование статьи
    :param post_id:
    :return:
    """
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            post.image_file = picture_file
        post.title = form.title.data
        post.description = form.description.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.description.data = post.description
        form.content.data = post.content
    image_file = url_for('static', filename='posts_img/' +
                                            post.image_file)
    return render_template('update_post.html', form=form,
                           image_file=image_file,
                           legend='Редактирование поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    """
    Удаление статьи
    :param post_id:
    :return:
    """
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.allpost'))


@posts.route("/comment/<int:comment_id>/delete", methods=['POST'])
@login_required
def delete_comment(comment_id):
    """
    Удаление комментария
    :param comment_id:
    :return:
    """
    comment = Comment.query.get_or_404(comment_id)
    if comment.username != current_user.username:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Ваш комментарий был удален!', 'success')
    return redirect(url_for('posts.allpost'))

first_flask_project/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from first_flask_project import db, bcrypt
from first_flask_project.models import User, Post
from first_flask_project.users.forms import RegistrationForm, LoginForm, \
    UpdateAccountForm, RequestResetForm, ResetPasswordForm
from first_flask_project.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    """
    Регистрация нового пользователя
    :return:
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана!'
              ' Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Регистрация', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    """
    Вход на сайт
    :return:
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page \
                else redirect(url_for('posts.allpost'))

        else:
            flash('Войти не удалось. Пожалуйста, '
                  'проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    """
    Вход в профиль пользователя
    :return:
    """
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.avatar_image = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user) \
            .order_by(Post.created.desc()) \
            .paginate(page=page, per_page=5)
    avatar_image = url_for('static', filename='profile_pics/' +
                                              current_user.avatar_image)
    return render_template('account.html', title='Аккаунт',
                           avatar_image=avatar_image, form=form, posts=posts,
                           user=user)


@users.route("/logout")
def logout():
    """
    Выход с сайта
    :return:
    """
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_posts(username):
    """
    Статьи пользователя
    :param username:
    :return:
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.created.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    """
    Запрос на изменение пароля
    :return:
    """
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с '
              'инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    """
    Проверка токена и изменение пароля
    :param token:
    :return:
    """
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).\
            decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! '
              'Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Сброс пароля', form=form)

first_flask_project/templates/includes/allposts_main.html
{% for post in posts.items %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{{ url_for('posts.post', post_id=post.id) }}">
                        <h2 class="post-title">
                            {{ post.title }}
                        </h2>
                    </a>
                    <div class="media">
                        <div class="media-body">
                            Автор поста:
                            <img class="rounded-circle account-img"
                                     src="{{ url_for('static', filename='profile_pics/' + post.author.avatar_image) }}"
                                     style="width: 6%;">
                            <a href="{{ url_for('users.user_posts', username=post.author.username) }}"
                               style="color: violet;">
                                {{ post.author.username }}
                            </a>
                        </div>
                    </div>
                    <p class="post-meta">
                        Опубликовано
                        {{ post.created.strftime('%d %B %Y %I:%M %p') }}
                    </p>
                    <p>Описание поста: {{ post.description }}</p>
                </div>
                <!-- Pager-->
                <div class="d-flex justify-content-end mb-4">
                    <a class="btn btn-primary text-uppercase"
                       href="{{ url_for('posts.post', post_id=post.id) }}">
                        Перейти к посту →
                    </a>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            </div>
        </div>
    </div>
{% endfor %}
<div class="container">
    <div style="text-align: center;">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-success mb-4"
                       href="{{ url_for('posts.allpost', page=page_num) }}">
                        {{ page_num }}
                    </a>
                {% else %}
                    <a class="btn btn-outline-success mb-4"
                       href="{{ url_for('posts.allpost', page=page_num) }}">
                        {{ page_num }}
                    </a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
</div>

first_flask_project/templates/includes/allposts_user.html
<h1 class="mb-3" style="text-align: center;">
    Посты опубликованные пользователем ({{ posts.total }} шт.):
</h1>
{% for post in posts.items %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{{ url_for('posts.post', post_id=post.id) }}">
                        <h2 class="post-title">
                            {{ post.title }}
                        </h2>
                    </a>
                    <div class="media">
                        <div class="media-body">
                            Автор поста:
                            <img class="rounded-circle account-img"
                                     src="{{ url_for('static', filename='profile_pics/' + post.author.avatar_image) }}"
                                     style="width: 6%;">
                            <a href="{{ url_for('users.user_posts', username=post.author.username) }}"
                               style="color: violet;">
                                <img class="rounded-circle account-img"
                                     src="{{ avatar_image }}"
                                     style="width: 10%;">
                                {{ post.author.username }}
                            </a>
                        </div>
                    </div>
                    <p class="post-meta">
                        Опубликовано
                        {{ post.created.strftime('%d %B %Y %I:%M %p') }}
                    </p>
                    <p>Описание поста: {{ post.description }}</p>
                </div>
                <!-- Pager-->
                <div class="d-flex justify-content-end mb-4">
                    <a class="btn btn-primary text-uppercase"
                       href="{{ url_for('posts.post', post_id=post.id) }}">
                        Перейти к посту →
                    </a>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            </div>
        </div>
    </div>
{% endfor %}
<div class="container">
    <div style="text-align: center;">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-success mb-4"
                       href="{{ url_for('posts.allpost', page=page_num) }}">
                        {{ page_num }}
                    </a>
                {% else %}
                    <a class="btn btn-outline-success mb-4"
                       href="{{ url_for('posts.allpost', page=page_num) }}">
                        {{ page_num }}
                    </a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
</div>

first_flask_project/templates/includes/content_404.html
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            <div class="post-preview" style="text-align: center;">
                <h1>Страница не найдена (404)</h1>
                <p>Такой страницы не существует</p>
            </div>
        </div>
    </div>
</div>

first_flask_project/templates/includes/content_account.html
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <div class="media">
                    <img class="rounded-circle account-img" src="{{ avatar_image }}">
                    <div class="media-body">
                        <h2 class="account-heading">
                            {{ current_user.username }}
                        </h2>
                        <p class="text-secondary">
                            {{ current_user.email }}
                        </p>
                    </div>
                </div>

                <div class="my-5">

                <form enctype="multipart/form-data"
                      method="POST">

                    {{ form.hidden_tag() }}

                    <legend class="border-bottom mb-4">
                        Редактирование данных
                    </legend>

                    <div class="form-floating">
                        {{ form.username.label(class="form-control-label") }}
                        <br>
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}

                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-floating">
                        {{ form.email.label(class="form-control-label") }}
                        <br>
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}

                            <div class="invalid-feedback">
                                An email is required.
                            </div>
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    {{ form.picture.label(style="margin: 10px 0px;") }}

                    <div class="form-floating">

                        {{ form.picture(class="form-control-file") }}

                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">
                                    {{ error }}
                                </span><br>
                            {% endfor %}

                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>

                    <br />

                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>

                </form>

                </div>
            </div>
        </div>
    </div>
</main>

first_flask_project/templates/includes/content_login.html
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="my-5">

                <form id="contactForm"
                      method="POST"
                      action="">

                    {{ form.hidden_tag() }}

                    <div class="form-floating">
                        {{ form.email.label(class="form-control-label") }}
                        <br>
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}

                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-floating">
                        {{ form.password.label(class="form-control-label") }}
                        <br>
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}

                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-floating">
                        <p class="text-muted ml-2">
                            <a href="{{ url_for('users.reset_request') }}"
                               style="color: #bc5656;">
                                Забыли пароль?
                            </a>
                        </p>
                    </div>

                    <!-- Submit Button-->
                    <div class="form-group">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                    <br>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info sub_log") }}
                    </div>
                    <br>
                    <small style="font-size: 20px; font-weight: 500;">
                        Для авторизации:
                        <a class="ml-2"
                           href="{{ url_for('users.register') }}"
                           style="color: blue">
                            Зарегистрируйтесь
                        </a>
                    </small>

                </form>

                </div>
            </div>
        </div>
    </div>
</main>

first_flask_project/templates/includes/content_reset_token.html
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="my-5">

                <form id="contactForm" method="POST" action="">

                    {{ form.hidden_tag() }}

                    <legend class="border-bottom mb-4">Изменение пароля</legend>

                    <div class="form-floating">
                        {{ form.password.label(class="form-control-label") }}
                        <br>
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}

                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-floating">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        <br>
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}

                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <br />

                    <!-- Submit Button-->

                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>

                </form>

                </div>
            </div>
        </div>
    </div>
</main>

first_flask_project/templates/includes/footer.html
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://geekbrains.ru">
                            <span class="fa-stack fa-lg">
                                <img class="rounded-circle account-img"
                                     src="{{ url_for('static', filename='assets/logo.png') }}"
                                     style="width: 83%;">
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://facebook.com">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">
                    Copyright &copy; Мой сайт 2022
                </div>
            </div>
        </div>
    </div>
</footer>

first_flask_project/templates/includes/header.html
<header class="masthead"
        style="background-image: url('../static/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5 "
         style="bottom: 60px">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Добро пожаловать!</h1>
                    <span class="subheading">
                        Здесь вы можете ознакомиться со статьями на разные темы.
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>

first_flask_project/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/home">Мой сайт</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        {% if current_user.is_authenticated %}
            <h4 style="margin-top: 10px; color: antiquewhite;">
                Привет, <img class="rounded-circle account-img"
                                     src="{{ url_for('static', filename='profile_pics/' + current_user.avatar_image) }}"
                                     style="width: 10%;">
                {{ current_user.username }}
            </h4>
        {% endif %}
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">

                {% if current_user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4"
                           href="{{url_for('posts.allpost') }}"
                           style="font-size: 0.85rem;">
                            <i class="fa fa-th"></i>
                            Посты
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4"
                           href="{{url_for('posts.new_post') }}"
                           style="font-size: 0.85rem;">
                            <i class="fa fa-plus"></i>
                            Создать пост
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4"
                           href="{{url_for('users.account') }}"
                           style="font-size: 0.85rem;">
                            <i class="fa fa-user"></i>
                            Профиль
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4"
                           href="{{ url_for('users.logout') }}"
                           style="font-size: 0.85rem;">
                            <i class="fa fa-sign-out"></i>
                            Выйти
                        </a>
                    </li>

                {% else %}

                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4"
                           href="{{url_for('users.login') }}"
                           style="font-size: 0.85rem;">
                            <i class="fa fa-sign-in"></i>
                            Войти
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4"
                           href="{{url_for('users.register') }}"
                           style="font-size: 0.85rem;">
                            Зарегистрироваться
                        </a>
                    </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>